name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install pip3
      run: |
        sudo add-apt-repository universe
        sudo apt install python3-pip
      
    - name: Install checkov
      run: pip3 install checkov

    - name: Check terraform, github-actions misconfigurations 
      run: checkov --directory . -o cli

    - name: Install kubescape
      run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

    - name: Check kubernetes misconfigurations
      run: kubescape scan .
      
